### ISSUE TITLE
Use tokenize instead of str.replace

### ISSUE THREAD

**Issue by sumezulike** [actopozipc/German-Python-Interpreter#2]
Hey, this is a fun idea! 
The current method of using `str.replace` on the 𝔔𝔲𝔢𝔩𝔩𝔠𝔬𝔡𝔢 will replace regardless of context tho, including occurences inside other strings. For example, `list` becomes `lis`.
 
I'd recommend you take a look at the [tokenize](https://docs.python.org/3/library/tokenize.html) module to parse everything and then replace the tokens instead of operating on the raw text. It's pretty easy to use.

**Comment by actopozipc** [comment]
Good argument, I'll put it on the TODO list and leave the issue open in the meantime.
